/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class AplikasiPenghitungKata extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPerhitunganKata
     */
    public AplikasiPenghitungKata() {
         initComponents();
    
    // Default: mode otomatis aktif
    otomatisRadioButton.setSelected(true);
    setAutoCount(true);

    // Tambahkan aksi untuk ubah mode
    otomatisRadioButton.addActionListener(e -> {
        setAutoCount(true);
        JOptionPane.showMessageDialog(this, "Mode otomatis diaktifkan — teks akan dihitung setiap kali berubah.");
    });

    manualRadioButton.addActionListener(e -> {
        setAutoCount(false);
        JOptionPane.showMessageDialog(this, "Mode manual diaktifkan — gunakan tombol Hitung untuk menghitung.");
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        hitungButton = new javax.swing.JButton();
        cariButton = new javax.swing.JButton();
        kataLabel = new javax.swing.JLabel();
        karakterLabel = new javax.swing.JLabel();
        kalimatLabel = new javax.swing.JLabel();
        paragrafLabel = new javax.swing.JLabel();
        hasilPencarianLabel = new javax.swing.JLabel();
        simpanButton = new javax.swing.JButton();
        pencarianField = new javax.swing.JTextField();
        otomatisRadioButton = new javax.swing.JRadioButton();
        manualRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setViewportView(textArea);

        textArea.setColumns(50);
        textArea.setLineWrap(true);
        textArea.setRows(15);
        textArea.setWrapStyleWord(true);
        scrollPane.setViewportView(textArea);

        hitungButton.setText("Hitung");
        hitungButton.setToolTipText("Hitung statistik teks");
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        cariButton.setText("Cari");
        cariButton.setToolTipText("Cari kata tertentu dalam teks");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        kataLabel.setText("Jumlah Kata: 0");

        karakterLabel.setText("Jumlah Karakter: 0");

        kalimatLabel.setText("Jumlah Kalimat: 0");

        paragrafLabel.setText("Jumlah Paragraf: 0");

        hasilPencarianLabel.setText("Hasil Pencarian: -");

        simpanButton.setText("Simpan");
        simpanButton.setToolTipText("Simpan teks dan hasil ke file");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        pencarianField.setToolTipText("Masukkan kata yang ingin dicari");

        buttonGroup1.add(otomatisRadioButton);
        otomatisRadioButton.setText("Hitung Otomatis ");

        buttonGroup1.add(manualRadioButton);
        manualRadioButton.setText("Hitung Manual");

        jLabel1.setText("APLIKASI PENGHITUNG KATA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(kataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kalimatLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(karakterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(paragrafLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pencarianField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hasilPencarianLabel)
                                    .addComponent(cariButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(otomatisRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manualRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kataLabel)
                            .addComponent(pencarianField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(karakterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kalimatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cariButton)
                        .addGap(23, 23, 23)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paragrafLabel)
                    .addComponent(hasilPencarianLabel))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungButton)
                    .addComponent(otomatisRadioButton)
                    .addComponent(manualRadioButton))
                .addGap(50, 50, 50)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(simpanButton)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        // TODO add your handling code here:
         hitungStatistik();
    }//GEN-LAST:event_hitungButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        simpanKeFile();
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        // TODO add your handling code here:
         cariKata();
    }//GEN-LAST:event_cariButtonActionPerformed

   // Variabel global listener
   private DocumentListener listener;

    // Method untuk mengatur apakah hitung otomatis aktif atau tidak
    private void setAutoCount(boolean aktif) {
        if (listener != null) {
            textArea.getDocument().removeDocumentListener(listener);
            listener = null;
        }

        if (aktif) {
            listener = new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    hitungStatistik();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    hitungStatistik();
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    hitungStatistik();
                }
            };
            textArea.getDocument().addDocumentListener(listener);
        }
    }

    
    
   // Method untuk setup DocumentListener
    private void setupDocumentListener(boolean aktif) {
        if (listener != null) {
            textArea.getDocument().removeDocumentListener(listener);
            listener = null;
        }

        if (aktif) {
            listener = new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    hitungStatistik();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    hitungStatistik();
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    hitungStatistik();
                }
            };
            textArea.getDocument().addDocumentListener(listener);
        }
    }


    // Method untuk menghitung statistik
    private void hitungStatistik() {
        String teks = textArea.getText().trim();
        
        // Hitung jumlah kata
        int jumlahKata = teks.isEmpty() ? 0 : teks.split("\\s+").length;
        
        // Hitung jumlah karakter (termasuk spasi)
        int jumlahKarakter = teks.length();
        
        // Hitung jumlah karakter (tanpa spasi)
        int jumlahKarakterTanpaSpasi = teks.replaceAll("\\s+", "").length();
        
        // Hitung jumlah kalimat
        int jumlahKalimat = teks.isEmpty() ? 0 : teks.split("[.!?]+").length;
        
        // Hitung jumlah paragraf
        int jumlahParagraf = teks.isEmpty() ? 0 : teks.split("\n\n").length;
        if (jumlahParagraf == 0 && !teks.isEmpty()) jumlahParagraf = 1;

        // Update label
        kataLabel.setText("Jumlah Kata: " + jumlahKata);
        karakterLabel.setText("Jumlah Karakter: " + jumlahKarakter + " (tanpa spasi: " + jumlahKarakterTanpaSpasi + ")");
        kalimatLabel.setText("Jumlah Kalimat: " + jumlahKalimat);
        paragrafLabel.setText("Jumlah Paragraf: " + jumlahParagraf);
    }

    // Method untuk mencari kata
    private void cariKata() {
        String kataDicari = pencarianField.getText().trim();
        String teks = textArea.getText();
        
        if (kataDicari.isEmpty()) {
            hasilPencarianLabel.setText("Hasil Pencarian: Masukkan kata yang dicari");
            return;
        }

        // Hitung kemunculan kata
        int jumlahKemunculan = 0;
        if (!teks.isEmpty()) {
            String[] kataArray = teks.split("\\s+");
            for (String kata : kataArray) {
                if (kata.equalsIgnoreCase(kataDicari)) {
                    jumlahKemunculan++;
                }
            }
        }

        hasilPencarianLabel.setText("Hasil Pencarian: '" + kataDicari + "' ditemukan " + jumlahKemunculan + " kali");
    }

    // Method untuk menyimpan ke file
    private void simpanKeFile() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Teks dan Hasil");

        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            try {
                String filePath = fileChooser.getSelectedFile().getAbsolutePath();
                if (!filePath.endsWith(".txt")) {
                    filePath += ".txt";
                }

                BufferedWriter writer = new BufferedWriter(new FileWriter(filePath));
                
                // Tulis teks asli
                writer.write("=== TEKS ASLI ===\n");
                writer.write(textArea.getText());
                writer.write("\n\n=== HASIL PERHITUNGAN ===\n");
                writer.write(kataLabel.getText() + "\n");
                writer.write(karakterLabel.getText() + "\n");
                writer.write(kalimatLabel.getText() + "\n");
                writer.write(paragrafLabel.getText() + "\n");
                writer.write(hasilPencarianLabel.getText() + "\n");
                writer.write("\n=== BRAINMATICS - IImukonputer.Com ===\n");
                
                writer.close();
                
                JOptionPane.showMessageDialog(this, 
                    "File berhasil disimpan di: " + filePath, 
                    "Sukses", 
                    JOptionPane.INFORMATION_MESSAGE);
                    
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, 
                    "Error menyimpan file: " + ex.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenghitungKata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cariButton;
    private javax.swing.JLabel hasilPencarianLabel;
    private javax.swing.JButton hitungButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kalimatLabel;
    private javax.swing.JLabel karakterLabel;
    private javax.swing.JLabel kataLabel;
    private javax.swing.JRadioButton manualRadioButton;
    private javax.swing.JRadioButton otomatisRadioButton;
    private javax.swing.JLabel paragrafLabel;
    private javax.swing.JTextField pencarianField;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
